obj-$(CONFIG_POLARFIRE_SOC_SYS_CTRL)	+= mpfs-sys-controller.o
obj-$(CONFIG_POLARFIRE_SOC_GENERIC_SERVICE)	+= mpfs-generic-service.o
obj-$(CONFIG_POLARFIRE_SOC_SYSCONS)	+= mpfs-control-scb.o mpfs-mss-top-sysreg.o
