obj-$(CONFIG_POLARFIRE_SOC_SYS_CTRL)	+= mpfs-sys-controller.o
obj-$(CONFIG_POLARFIRE_SOC_SERIAL_NUMBER) += mpfs-serial-number.o
obj-$(CONFIG_POLARFIRE_SOC_FPGA_DIGEST)	+= mpfs-fpga-digest.o
obj-$(CONFIG_POLARFIRE_SOC_FPGA_CERT)	+= mpfs-device-cert.o
obj-$(CONFIG_POLARFIRE_SOC_SIGNATURE)	+= mpfs-signature.o
