/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for rsaprivkey
 */
#include <linux/asn1_decoder.h>

extern const struct asn1_decoder rsaprivkey_decoder;

extern int rsa_get_d(void *, size_t, unsigned char, const void *, size_t);
extern int rsa_get_e(void *, size_t, unsigned char, const void *, size_t);
extern int rsa_get_n(void *, size_t, unsigned char, const void *, size_t);

